### ISSUE TITLE
WebRTC --- apprtc.appspot.org

### ISSUE THREAD

**Issue by Yaakov-Belch** [Yaakov-Belch/NetFree-issues#1]
Please enable live video chats via: https://apprtc.appspot.com/r/chavruta

**Comment by Yaakov-Belch** [comment]
Marco opened some of the necessary URLs --- but there are still some issues when I try to connect.  Here is a recording of the network traffic:

http://netfree.link/user#/tools/traffic/view/b4b1847635de2682da35133efb4d3fe77f2c9e71

The application says:

    No TURN server; unlikely that media will traverse networks.

The console log complains:

    GET https://computeengineondemand.appspot.com/turn?username=039443198&key=4080218913 503 (Service Unavailable)

It seems that the URL https://computeengineondemand.appspot.com/turn is still blocked.

**Comment by macroshadow** [comment]
Check it now. I opened computeengineondemand.appspot.com

**Comment by Yaakov-Belch** [comment]
Tested: It works.

Thanks a lot!
